### ISSUE TITLE
bug: hints break ui-router

### ISSUE THREAD

**Issue by ayackel** [angular/batarang#186]
Can we have a way to disable hints?  Angular-hint has some hard-coded directive types that are incompatible with ui-router.  My app fails to load because ng-grid cannot find it's controller in the scope.  With batarang disabled it is in the scope.  I think this is due to the use of 'ui-view' instead of 'ng-view'.

```
 TypeError: Cannot set property 'gridDim' of undefined
    at ngGridDirectives.directive.ngGridDirective.compile.pre (http://localhost:9000/bower_components/ng-grid/build/ng-grid.js:2962:37)
    at invokeLinkFn (http://localhost:9000/bower_components/angular/angular.js:8194:9)
    at nodeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7685:11)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7062:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7065:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7065:13)
    at compositeLinkFn (http://localhost:9000/bower_components/angular/angular.js:7065:13)
    at publicLinkFn (http://localhost:9000/bower_components/angular/angular.js:6941:30)
    at newCompile (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2622:22)
    at compile (http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.js:3905:9) <div class="gridStyle ng-scope" ng-grid="workTypeCtrl.gridOptions">
```

**Comment by SomeKittens** [comment]
Batarang works with UI-Router now.
