### ISSUE TITLE
error in expression "move (-1)"

### ISSUE THREAD

**Issue by orochies** [angular/batarang#230]
when I select Enable, and charge the web, on the console trace the following:

<pre>
Error: [$parse:ueoe] Unexpected end of expression: move(
http://errors.angularjs.org/1.3.14/$parse/ueoe?p0=move(
    at REGEX_STRING_REGEXP (http://localhost:1908/Scripts/angular.js:63:12)
    at Parser.peekToken (http://localhost:1908/Scripts/angular.js:12018:13)
    at Parser.functionCall (http://localhost:1908/Scripts/angular.js:12318:14)
    at Parser.primary (http://localhost:1908/Scripts/angular.js:11995:24)
    at Parser.unary (http://localhost:1908/Scripts/angular.js:12271:19)
    at Parser.multiplicative (http://localhost:1908/Scripts/angular.js:12254:21)
    at Parser.additive (http://localhost:1908/Scripts/angular.js:12245:21)
    at Parser.relational (http://localhost:1908/Scripts/angular.js:12236:21)
    at Parser.equality (http://localhost:1908/Scripts/angular.js:12227:21)
    at Parser.logicalAND (http://localhost:1908/Scripts/angular.js:12218:21) &lt;a href="#" ng-click="move(-1)" tabindex="-1"&gt;
</pre>

when I change the number -1 of the expression to another non-negative, the error disappears

**Comment by gary-b** [comment]
I found a (kind off) similar error when testing an app found on builtwith.angularjs.org:
https://m.auspost.com.au/view/home
Only when Batarang is enabled does the following error show up on the console:
"Error: [$parse:lexerr] Lexer Error: Unterminated quote at columns 10-15 ['menu] in expression [showPanel('menu].
http://errors.angularjs.org/1.2.20/$parse/lexerr?p0=Unterminated%20quote&p1=s%2010-15%20%5B'menu%5D&p2=showPanel('menu
    at https://m.auspost.com.au/js/app-min.js:1:675
    at od.throwError (https://m.auspost.com.au/js/app-min.js:3:22687)
    at od.readString (https://m.auspost.com.au/js/app-min.js:3:24535)
    at od.lex (https://m.auspost.com.au/js/app-min.js:3:21392)
    at pd.parse (https://m.auspost.com.au/js/app-min.js:3:24767)
    at $get (https://m.auspost.com.au/js/app-min.js:2:18771)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1676:17
    at Array.forEach (native)
    at ngEventHandler (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1671:20)
    at s (https://m.auspost.com.au/js/app-min.js:1:26805) <a ng-click=""showPanel('menu-help')"">"
	
It then seems that Batarang cannot be disabled on that page without disabling it in chrome completely.

**Comment by erwinmombay** [comment]
related: https://github.com/angular/angularjs-batarang/issues/232

**Comment by stephan-hof** [comment]
I had the same issue and from my point of view this happens inside hint.js
https://github.com/angular/angular-hint/issues/98

**Comment by gamebox** [comment]
Getting this same error.  Using Angular-UI Bootstrap Datepicker.  Thankfully StackExchange exists and I only lost 15 minutes on this.

**Comment by erwinmombay** [comment]
fix landed in https://github.com/angular/angular-hint/commit/26cfc749113a599a1e11a587091c558ee2e499b6
