### ISSUE TITLE
Breaks my app

### ISSUE THREAD

**Issue by dolzenko** [angular/batarang#250]
When installed it breaks my app with

```
Error: [$parse:ueoe] Unexpected end of expression: audience.active?audience
http://errors.angularjs.org/1.4.3/$parse/ueoe?p0=audience.active%3Faudience
    at REGEX_STRING_REGEXP (http://localhost:3000/ui/assets/app.js:3179:12)
    at Object.AST.consume (http://localhost:3000/ui/assets/app.js:15999:13)
    at Object.AST.ternary (http://localhost:3000/ui/assets/app.js:15810:16)
    at Object.AST.assignment (http://localhost:3000/ui/assets/app.js:15797:23)
    at Object.AST.expression (http://localhost:3000/ui/assets/app.js:15793:17)
    at Object.AST.filterChain (http://localhost:3000/ui/assets/app.js:15784:21)
    at Object.AST.expressionStatement (http://localhost:3000/ui/assets/app.js:15780:62)
    at Object.AST.program (http://localhost:3000/ui/assets/app.js:15772:24)
    at Object.AST.ast (http://localhost:3000/ui/assets/app.js:15759:22)
    at Object.ASTCompiler.compile (http://localhost:3000/ui/assets/app.js:16211:31) <a ng-class="audience.active ? 'label-success' : ''" ng-bind="audience.active ? 'Active' : 'Inactive'" ng-click="audience.active ? audience.deactivate() : audience.activate()" ng-attr-title="Click to {{audience.active ? 'Pause' : 'Unpause'}}" class="label label-default ng-binding">
```

All works fine if I uninstall the extension.  Also it seems particularly related to the `ng-click` clause in the above code, because when I remove that the error disappears too.

**Comment by SomeKittens** [comment]
(specifically, this snippet?  `ng-click="audience.active ? audience.deactivate() : audience.activate()"`)

Dealing with this is tricky, as Batarang currently assumes you won't have any logic in your click events.  Angular's parser *allows* for that, but you may want to add a `audience.toggle()` instead of a ternary in ng-click.

@erwinmombay has been fixing bugs in that area.

**Comment by jirkahronik** [comment]
I confirm Batarang has difficulties handling ternary operator in the ng-click directive.
To replicate the issue, use ng-table's demo page with Batarang on:
http://ng-table.com/#/demo/5-8

Couldn't you use the same expression parser as Angular itself?

**Comment by SomeKittens** [comment]
@jirkahronik The purpose of our parser is to find undefined expressions, where Angular's parser swallows errors (and can make debugging tricky).

**Comment by erwinmombay** [comment]
ill look into this.

**Comment by erwinmombay** [comment]
fix landed in hint https://github.com/angular/angular-hint/commit/73a31957aa72f4d5f1d391c0528e5e01e8751ce5
