### ISSUE TITLE
isUndefined is not a function

### ISSUE THREAD

**Issue by oliversalzburg** [angular/batarang#312]
```
Uncaught ReferenceError: isUndefined is not defined
    at toDebugString (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:96:14)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:191:16
    at Array.map (native)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:190:46
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:313:17
    at ensure (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:234:38)
    at Object.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:311:14)
    at Object.angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1184:31)
    at Object.angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1334:38)
```
Seems like it wants `angular.isUndefined` or something.

**Comment by gkalpak** [comment]
Ooops, I missed that in f04d250ec :disappointed:
I'll fix it on the next release. Thx for reporting!
