### ISSUE TITLE
Issue with humanReadable

### ISSUE THREAD

**Issue by btford** [angular/batarang#61]
Came across this while adding apps to BWA.

On this site: http://www.meomap.net/#!/map?category=1

```
TypeError: Cannot read property 'exp' of undefined
    at watchFnToHumanReadableString (http://www.meomap.net/#!/map?category=1:680:19)
    at Object.$delegate.__proto__.$watch (http://www.meomap.net/#!/map?category=1:712:28)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:147:331
    at j (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:43:458)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:39:248)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:39:265)
    at j (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:43:398)
    at e (https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:39:248)
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:38:312
    at https://ajax.googleapis.com/ajax/libs/angularjs/1.0.6/angular.min.js:144:135 <div class="alert alert-success" ng-show="((placesMsg))"> 
```

**Comment by mtevrst** [comment]
I am still facing this issue. Why was this closed?

**Comment by SomeKittens** [comment]
@mtevrst as @btford says, this function no longer exists.  You're probably running an old version.
